/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, } from "@icp-sdk/core/agent";

import { idlFactory, } from "./declarations/backend.did";








function some(value) {
    return {
        __kind__: "Some",
        value: value
    };
}
function none() {
    return {
        __kind__: "None"
    };
}
function isNone(option) {
    return option.__kind__ === "None";
}
function isSome(option) {
    return option.__kind__ === "Some";
}
function unwrap(option) {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some(value) {
    return [
        value
    ];
}
function candid_none() {
    return [];
}
function record_opt_to_undefined(arg) {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob;
    directURL;
    onProgress = undefined;
     constructor(directURL, blob){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url) {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob) {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
     async getBytes() {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
     getDirectURL() {
        return this.directURL;
    }
     withUploadProgress(onProgress) {
        this.onProgress = onProgress;
        return this;
    }
}





























































export var AppointmentStatus; (function (AppointmentStatus) {
    const cancelled = "cancelled"; AppointmentStatus["cancelled"] = cancelled;
    const pending = "pending"; AppointmentStatus["pending"] = pending;
    const rescheduled = "rescheduled"; AppointmentStatus["rescheduled"] = rescheduled;
    const approved = "approved"; AppointmentStatus["approved"] = approved;
})(AppointmentStatus || (AppointmentStatus = {}));
export var UserRole; (function (UserRole) {
    const admin = "admin"; UserRole["admin"] = admin;
    const user = "user"; UserRole["user"] = user;
    const guest = "guest"; UserRole["guest"] = guest;
})(UserRole || (UserRole = {}));


































export class Backend  {
    constructor( actor,  _uploadFile,  _downloadFile,  processError){;this.actor = actor;this._uploadFile = _uploadFile;this._downloadFile = _downloadFile;this.processError = processError;}
    async _initializeAccessControl() {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async approveAppointment(arg0, arg1) {
        if (this.processError) {
            try {
                const result = await this.actor.approveAppointment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveAppointment(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0, arg1) {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelAppointment(arg0, arg1) {
        if (this.processError) {
            try {
                const result = await this.actor.cancelAppointment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelAppointment(arg0, arg1);
            return result;
        }
    }
    async createDoctor(arg0) {
        if (this.processError) {
            try {
                const result = await this.actor.createDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDoctor(arg0);
            return result;
        }
    }
    async createPatient(arg0) {
        if (this.processError) {
            try {
                const result = await this.actor.createPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPatient(arg0);
            return result;
        }
    }
    async createService(arg0) {
        if (this.processError) {
            try {
                const result = await this.actor.createService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createService(arg0);
            return result;
        }
    }
    async getAdminActivityLog() {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminActivityLog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminActivityLog();
            return result;
        }
    }
    async getAdminDashboardStats() {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminDashboardStats();
            return result;
        }
    }
    async getAllAppointments() {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppointments();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppointments();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDoctors() {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDoctors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDoctors();
            return result;
        }
    }
    async getAllPatients() {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPatients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPatients();
            return result;
        }
    }
    async getAllServices() {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServices();
            return result;
        }
    }
    async getAppointmentsByStatus(arg0) {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByStatus(to_candid_AppointmentStatus_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByStatus(to_candid_AppointmentStatus_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile() {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole() {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoctor(arg0) {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctor(arg0);
            return result;
        }
    }
    async getPatient(arg0) {
        if (this.processError) {
            try {
                const result = await this.actor.getPatient(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatient(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatientAppointments(arg0) {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientAppointments(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientAppointments(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPregnancyTracker(arg0) {
        if (this.processError) {
            try {
                const result = await this.actor.getPregnancyTracker(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPregnancyTracker(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getService(arg0) {
        if (this.processError) {
            try {
                const result = await this.actor.getService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getService(arg0);
            return result;
        }
    }
    async getUserProfile(arg0) {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeSystem() {
        if (this.processError) {
            try {
                const result = await this.actor.initializeSystem();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeSystem();
            return result;
        }
    }
    async isCallerAdmin() {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async rescheduleAppointment(arg0, arg1, arg2, arg3) {
        if (this.processError) {
            try {
                const result = await this.actor.rescheduleAppointment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rescheduleAppointment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async saveCallerUserProfile(arg0) {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setPregnancyTracker(arg0, arg1, arg2) {
        if (this.processError) {
            try {
                const result = await this.actor.setPregnancyTracker(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPregnancyTracker(arg0, arg1, arg2);
            return result;
        }
    }
    async submitAppointmentRequest(arg0, arg1, arg2, arg3, arg4, arg5, arg6) {
        if (this.processError) {
            try {
                const result = await this.actor.submitAppointmentRequest(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAppointmentRequest(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateDoctor(arg0, arg1) {
        if (this.processError) {
            try {
                const result = await this.actor.updateDoctor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDoctor(arg0, arg1);
            return result;
        }
    }
    async updatePatient(arg0, arg1) {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatient(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatient(arg0, arg1);
            return result;
        }
    }
    async updateService(arg0, arg1) {
        if (this.processError) {
            try {
                const result = await this.actor.updateService(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateService(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AppointmentStatus_n6(_uploadFile, _downloadFile, value) {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n4(_uploadFile, _downloadFile, value) {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile, _downloadFile, value) {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile, _downloadFile, value) {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile, _downloadFile, value) {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile, _downloadFile, value) {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile, _downloadFile, value









)









 {
    return {
        id: value.id,
        status: from_candid_AppointmentStatus_n6(_uploadFile, _downloadFile, value.status),
        doctorId: value.doctorId,
        requestedTimeSlot: value.requestedTimeSlot,
        patientId: value.patientId,
        createdAt: value.createdAt,
        adminNote: value.adminNote,
        requestedDate: value.requestedDate,
        serviceId: value.serviceId
    };
}
function from_candid_variant_n12(_uploadFile, _downloadFile, value





) {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile, _downloadFile, value







) {
    return "cancelled" in value ? AppointmentStatus.cancelled : "pending" in value ? AppointmentStatus.pending : "rescheduled" in value ? AppointmentStatus.rescheduled : "approved" in value ? AppointmentStatus.approved : value;
}
function from_candid_vec_n3(_uploadFile, _downloadFile, value) {
    return value.map((x)=>from_candid_Appointment_n4(_uploadFile, _downloadFile, x));
}
function to_candid_AppointmentStatus_n8(_uploadFile, _downloadFile, value) {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile, _downloadFile, value) {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile, _downloadFile, value)





 {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile, _downloadFile, value)







 {
    return value == AppointmentStatus.cancelled ? {
        cancelled: null
    } : value == AppointmentStatus.pending ? {
        pending: null
    } : value == AppointmentStatus.rescheduled ? {
        rescheduled: null
    } : value == AppointmentStatus.approved ? {
        approved: null
    } : value;
}






export function createActor(canisterId, _uploadFile, _downloadFile, options = {}) {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
