/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminActivityLog {
  'action' : string,
  'performedBy' : Principal,
  'timestamp' : Time,
}
export interface AdminDashboardStats {
  'totalPatients' : bigint,
  'todaysAppointments' : bigint,
  'doctorsCount' : bigint,
  'totalRevenue' : bigint,
}
export interface Appointment {
  'id' : bigint,
  'status' : AppointmentStatus,
  'doctorId' : string,
  'requestedTimeSlot' : string,
  'patientId' : Principal,
  'createdAt' : Time,
  'adminNote' : string,
  'requestedDate' : string,
  'serviceId' : string,
}
export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'rescheduled' : null } |
  { 'approved' : null };
export interface Doctor {
  'name' : string,
  'timingEnd' : string,
  'qualifications' : string,
  'isActive' : boolean,
  'experience' : bigint,
  'specialization' : string,
  'timingStart' : string,
  'isPlaceholder' : boolean,
}
export interface Patient {
  'id' : Principal,
  'name' : string,
  'email' : string,
  'medicalHistory' : string,
  'address' : string,
  'phone' : string,
}
export interface PregnancyTracker {
  'estimatedDueDate' : Time,
  'weekDescription' : string,
  'currentWeek' : bigint,
  'lmpDate' : Time,
}
export interface Service {
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'category' : string,
  'preparation' : string,
  'price' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'approveAppointment' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelAppointment' : ActorMethod<[bigint, string], undefined>,
  'createDoctor' : ActorMethod<[Doctor], undefined>,
  'createPatient' : ActorMethod<[Patient], undefined>,
  'createService' : ActorMethod<[Service], undefined>,
  'getAdminActivityLog' : ActorMethod<[], Array<AdminActivityLog>>,
  'getAdminDashboardStats' : ActorMethod<[], AdminDashboardStats>,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllDoctors' : ActorMethod<[], Array<Doctor>>,
  'getAllPatients' : ActorMethod<[], Array<Patient>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAppointmentsByStatus' : ActorMethod<
    [AppointmentStatus],
    Array<Appointment>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDoctor' : ActorMethod<[string], Doctor>,
  'getPatient' : ActorMethod<[Principal], [] | [Patient]>,
  'getPatientAppointments' : ActorMethod<[Principal], Array<Appointment>>,
  'getPregnancyTracker' : ActorMethod<[Principal], [] | [PregnancyTracker]>,
  'getService' : ActorMethod<[string], Service>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeSystem' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rescheduleAppointment' : ActorMethod<
    [bigint, string, string, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setPregnancyTracker' : ActorMethod<[Principal, Time, string], undefined>,
  'submitAppointmentRequest' : ActorMethod<
    [string, string, string, string, string, string, string],
    bigint
  >,
  'updateDoctor' : ActorMethod<[string, Doctor], undefined>,
  'updatePatient' : ActorMethod<[Principal, Patient], undefined>,
  'updateService' : ActorMethod<[string, Service], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];