/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Doctor = IDL.Record({
  'name' : IDL.Text,
  'timingEnd' : IDL.Text,
  'qualifications' : IDL.Text,
  'isActive' : IDL.Bool,
  'experience' : IDL.Nat,
  'specialization' : IDL.Text,
  'timingStart' : IDL.Text,
  'isPlaceholder' : IDL.Bool,
});
export const Patient = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'medicalHistory' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Service = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'category' : IDL.Text,
  'preparation' : IDL.Text,
  'price' : IDL.Nat,
});
export const Time = IDL.Int;
export const AdminActivityLog = IDL.Record({
  'action' : IDL.Text,
  'performedBy' : IDL.Principal,
  'timestamp' : Time,
});
export const AdminDashboardStats = IDL.Record({
  'totalPatients' : IDL.Nat,
  'todaysAppointments' : IDL.Nat,
  'doctorsCount' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
});
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'rescheduled' : IDL.Null,
  'approved' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'status' : AppointmentStatus,
  'doctorId' : IDL.Text,
  'requestedTimeSlot' : IDL.Text,
  'patientId' : IDL.Principal,
  'createdAt' : Time,
  'adminNote' : IDL.Text,
  'requestedDate' : IDL.Text,
  'serviceId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const PregnancyTracker = IDL.Record({
  'estimatedDueDate' : Time,
  'weekDescription' : IDL.Text,
  'currentWeek' : IDL.Nat,
  'lmpDate' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'approveAppointment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelAppointment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'createDoctor' : IDL.Func([Doctor], [], []),
  'createPatient' : IDL.Func([Patient], [], []),
  'createService' : IDL.Func([Service], [], []),
  'getAdminActivityLog' : IDL.Func([], [IDL.Vec(AdminActivityLog)], ['query']),
  'getAdminDashboardStats' : IDL.Func([], [AdminDashboardStats], ['query']),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getAppointmentsByStatus' : IDL.Func(
      [AppointmentStatus],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDoctor' : IDL.Func([IDL.Text], [Doctor], ['query']),
  'getPatient' : IDL.Func([IDL.Principal], [IDL.Opt(Patient)], ['query']),
  'getPatientAppointments' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getPregnancyTracker' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PregnancyTracker)],
      ['query'],
    ),
  'getService' : IDL.Func([IDL.Text], [Service], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeSystem' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rescheduleAppointment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPregnancyTracker' : IDL.Func([IDL.Principal, Time, IDL.Text], [], []),
  'submitAppointmentRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateDoctor' : IDL.Func([IDL.Text, Doctor], [], []),
  'updatePatient' : IDL.Func([IDL.Principal, Patient], [], []),
  'updateService' : IDL.Func([IDL.Text, Service], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Doctor = IDL.Record({
    'name' : IDL.Text,
    'timingEnd' : IDL.Text,
    'qualifications' : IDL.Text,
    'isActive' : IDL.Bool,
    'experience' : IDL.Nat,
    'specialization' : IDL.Text,
    'timingStart' : IDL.Text,
    'isPlaceholder' : IDL.Bool,
  });
  const Patient = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'medicalHistory' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Service = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'category' : IDL.Text,
    'preparation' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Time = IDL.Int;
  const AdminActivityLog = IDL.Record({
    'action' : IDL.Text,
    'performedBy' : IDL.Principal,
    'timestamp' : Time,
  });
  const AdminDashboardStats = IDL.Record({
    'totalPatients' : IDL.Nat,
    'todaysAppointments' : IDL.Nat,
    'doctorsCount' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
  });
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'rescheduled' : IDL.Null,
    'approved' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'status' : AppointmentStatus,
    'doctorId' : IDL.Text,
    'requestedTimeSlot' : IDL.Text,
    'patientId' : IDL.Principal,
    'createdAt' : Time,
    'adminNote' : IDL.Text,
    'requestedDate' : IDL.Text,
    'serviceId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const PregnancyTracker = IDL.Record({
    'estimatedDueDate' : Time,
    'weekDescription' : IDL.Text,
    'currentWeek' : IDL.Nat,
    'lmpDate' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'approveAppointment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelAppointment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'createDoctor' : IDL.Func([Doctor], [], []),
    'createPatient' : IDL.Func([Patient], [], []),
    'createService' : IDL.Func([Service], [], []),
    'getAdminActivityLog' : IDL.Func(
        [],
        [IDL.Vec(AdminActivityLog)],
        ['query'],
      ),
    'getAdminDashboardStats' : IDL.Func([], [AdminDashboardStats], ['query']),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getAppointmentsByStatus' : IDL.Func(
        [AppointmentStatus],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDoctor' : IDL.Func([IDL.Text], [Doctor], ['query']),
    'getPatient' : IDL.Func([IDL.Principal], [IDL.Opt(Patient)], ['query']),
    'getPatientAppointments' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getPregnancyTracker' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PregnancyTracker)],
        ['query'],
      ),
    'getService' : IDL.Func([IDL.Text], [Service], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeSystem' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rescheduleAppointment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPregnancyTracker' : IDL.Func([IDL.Principal, Time, IDL.Text], [], []),
    'submitAppointmentRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateDoctor' : IDL.Func([IDL.Text, Doctor], [], []),
    'updatePatient' : IDL.Func([IDL.Principal, Patient], [], []),
    'updateService' : IDL.Func([IDL.Text, Service], [], []),
  });
};

export const init = ({ IDL }) => { return []; };